DROP DATABASE IF EXISTS SerpisFP;
CREATE DATABASE SerpisFP;
USE SerpisFP;

DROP TABLE IF EXISTS GRUPO_IE28;
DROP TABLE IF EXISTS ALUMNO_IE28;
DROP TABLE IF EXISTS PROYECTO_CONVOCATORIA_IE28;
DROP TABLE IF EXISTS MODULO_IE28;
DROP TABLE IF EXISTS MATRICULA_IE28;

CREATE TABLE GRUPO_IE28
(
    CODGRUPO INT AUTO_INCREMENT NOT NULL,
    DESCRIPCION VARCHAR (50),
    AULA VARCHAR (10),
    PRIMARY KEY (CODGRUPO)
);

CREATE TABLE ALUMNO_IE28
(
    NIA VARCHAR (10),
    NOMBRE VARCHAR (50),
    APELLIDOS VARCHAR (50),
    CODGRUPO INT NOT NULL,
    PRIMARY KEY (NIA),
    CONSTRAINT fk_codGrupo_far FOREIGN KEY (CODGRUPO) REFERENCES GRUPO_IE28(CODGRUPO) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE MODULO_IE28
(
    CODMODULO INT AUTO_INCREMENT NOT NULL,
    DESCRIPCION VARCHAR (50),
    NUMHORAS INT,
    PRIMARY KEY (CODMODULO)
);      

CREATE TABLE MATRICULA_IE28
(
    NIA VARCHAR (10),
    CODMODULO INT,
    DESCRIPCION VARCHAR (50),
    PRIMARY KEY (NIA,CODMODULO),
    CONSTRAINT fk_nia_Alu FOREIGN KEY (NIA) REFERENCES ALUMNO_IE28(NIA) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_modulo_cod FOREIGN KEY (CODMODULO) REFERENCES MODULO_IE28(CODMODULO) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE PROYECTO_CONVOCATORIA_IE28xs
(
    CODPROYECTO INT NOT NULL AUTO_INCREMENT,
    TITULO VARCHAR (200),
    NIA VARCHAR (10) NOT NULL UNIQUE,
    PRIMARY KEY (CODPROYECTO),
    CONSTRAINT fk_nia_Alumno FOREIGN KEY (NIA) REFERENCES ALUMNO_IE28(NIA) ON DELETE CASCADE ON UPDATE CASCADE
);


INSERT INTO GRUPO_IE28 (DESCRIPCION, AULA) VALUES
('2DAMC', 'A1'),
('2DAMR', 'B2'),
('2ASIRC', 'C3');

INSERT INTO ALUMNO_IE28 (NIA, NOMBRE, APELLIDOS, CODGRUPO) VALUES
('12345678', 'ISLAM', 'EL MRABET LARHZAOUI', 1),  
('12345687', 'DAVID', 'GUAITA ONSURBE', 1),        
('12345876', 'HERMES', 'PEREZ PARRONDO', 1),       
('87654321', 'IGNACIO', 'PEREZ POSE', 1),         
('87654312', 'JORGE', 'SIERRA GARCÍA', 1), 
('12345645', 'Alumne', 'ALUMNE', 1);        

INSERT INTO ALUMNO_IE28 (NIA, NOMBRE, APELLIDOS, CODGRUPO) VALUES
('28765431', 'ANTONIO VICENTE', 'MOLINES MARTÍN', 1); 

INSERT INTO MODULO_IE28 (DESCRIPCION, NUMHORAS) VALUES
('ADA', 60),
('SGE', 70),
('PSP', 120),
('PM', 10),
('EIE', 80),
('DIN', 140);

INSERT INTO MATRICULA_IE28 (NIA, CODMODULO, DESCRIPCION) VALUES
('28765431', 1, 'ADA'),  
('12345678', 1, 'ADA'),  
('28765431', 2, 'PSP');  

INSERT INTO PROYECTO_CONVOCATORIA_IE28 (TITULO, NIA) VALUES
('App per a reptes personals', '28765431'); 

